<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>movensys_navigation_perception</name>
  <version>0.0.0</version>
  <description>movensys_navigation_perception</description>
  <maintainer email="mfikih@movensys.com">LebahGanteng88</maintainer>
  <maintainer email="sjhwang1236@gmail.com">noah</maintainer>
  <license>MIT License</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
	
  <exec_depend>ros2launch</exec_depend>

  <!-- visual_slam.launch.py (use_cuvslam:=true; isaac-ros_* images only) -->
  <exec_depend>isaac_ros_visual_slam</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>