differential_drive:
  ros__parameters:
    use_sim_time: true
    wheel_left_name: "wheel_l_joint"
    wheel_right_name: "wheel_r_joint"
    wheel_radius: 0.09
    wheel_to_wheel: 0.24
    topic_joint_states: "/joint_states"
    topic_odom_encoder: "/odom_encoder"
    topic_motor_commands: "/velocity_controller/commands"
    topic_cmd_vel_safe: "/cmd_vel_safe"
