<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>movensys_navigation_nav2_config</name>
  <version>0.1.0</version>
  <description>Movensys Navigation</description>
  <maintainer email="lab@ntrex.co.kr">ntrex</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>urdf</depend>
  <depend>xacro</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros2_control</depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>

  <!-- base.launch.py -->
  <exec_depend>movensys_navigation_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <!-- mapping.launch.py -->
  <exec_depend>slam_toolbox</exec_depend>

  <exec_depend>movensys_navigation_perception</exec_depend>

  <!-- navigation.launch.py -->
  <exec_depend>navigation2</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
